monsterlist = [
	'monster/4_hopy kid.groovy',// 小独角兽
	'monster/4_hopy.groovy',// 独角兽
	'monster/4_hopykid.groovy',// 龋乔 虐靛
	'monster/4_rabie.groovy',// 兔妖
	'monster/4_tobie.groovy',// 红兔妖
	'monster/5_mudy.groovy',// 土妖
	'monster/b_4_zzangpy.groovy',// 超级独角兽
	'monster/sb1_hopy.groovy',//  炉乔 
	'monster/5_bebechick.groovy',// 蹦蹦鸡
	'monster/5_cuepy.groovy',// 红独角兽
	'monster/5_mush.groovy',// 红蘑菇精
	'monster/5_mushroomghost.groovy',// 蘑菇精
	'monster/5_zeldy.groovy',// 透明妖
	'monster/6_arma.groovy',// 穿山甲
	'monster/6_papachick.groovy',// 啪啪鸡
	'monster/7_sen.groovy',// 路灯怪
	'monster/7_watermelon.groovy',// 西瓜太郎
	'monster/8_bigghost.groovy',// 魂魄
	'monster/8_egan.groovy',// 草帽怪
	'monster/8_ghost.groovy',// 鬼魂
	'monster/8_orbit.groovy',// 火眼怪
	'monster/10_minig.groovy',// 绿豆糕
	'monster/10_santagoblin-d.groovy',// 圣诞精灵(小)
	'monster/event_molly.groovy',// 莫利狼奶奶
	'monster/event_morif.groovy',// 精灵鼠小弟
	'monster/event_tobie.groovy',// 咯空配厚
	'monster/12_doral.groovy',// 双足虫
	'monster/12_mutantplant.groovy',// 变异植物
	'monster/14_hobgoblin.groovy',// 魔兽兵
	'monster/14_northgoblin.groovy',// 巨魔兽
	'monster/s2_hobgoblin.groovy',//  醛绊喉赴 
	'monster/sb2_hobgoblin.groovy',//  客老靛 绊喉赴 
	'monster/_14_h_hobgoblin.groovy',// 锤子巨魔兽
	'monster/15_mutantrabie.groovy',// 变异兔妖
	'monster/b_15_mutantrabie.groovy',// 超级变异兔子
	'monster/16_mutanttree.groovy',// 树根怪
	'monster/17_hauntingmaple.groovy',// 红木精
	'monster/17_hauntingplant.groovy',// 绿木精
	'monster/17_plant.groovy',// 绿木精怪
	'monster/17_planty.groovy',// 红木精怪
	'monster/_17_h_hauntingplant.groovy',// 锤子树
	'monster/18_corrupt.groovy',// 青骷髅
	'monster/18_skeleton.groovy',// 红骷髅
	'monster/19_zombie.groovy',// 僵尸
	'monster/21_cokris.groovy',// 独眼蜈蚣
	'monster/22_beedog.groovy',// 蜂巢怪
	'monster/23_mephit.groovy',// 青精灵
	'monster/b_23_mephit.groovy',// 超级青精灵
	'monster/25_minigsilver.groovy',// 蓝豆糕
	'monster/b_25_minigsilver.groovy',// 超级蓝豆糕
	'monster/27_scorpion.groovy',// 蝎兽
	'monster/28_devilishtree.groovy',// 恶梦树
	'monster/28_plantlord.groovy',// 梦魇树
	'monster/b_28_plantlord.groovy',// 超级木精怪
	'monster/29_hobgoblinchief.groovy',// 魔斧怪
	'monster/29_northgoblinchielf.groovy',// 魔锤兵
	'monster/30_leech.groovy',// 入地龙
	'monster/30_santagoblin-c.groovy',// 圣诞精灵
	'monster/31_decoy.groovy',// 浮灵
	'monster/s3_decoy.groovy',//  叼内捞 
	'monster/sb3_decoy.groovy',//  钙矫肛 叼内捞 
	'monster/_31_h_decoy.groovy',// 锤子浮灵
	'monster/32_ghoul.groovy',// 盗贼
	'monster/b_32_ghoul.groovy',// 超级盗尸贼
	'monster/33_cyclops.groovy',// 独眼魔人
	'monster/b_33_cyclops.groovy',// 超级独眼魔人
	'monster/34_web.groovy',// 大头蜘蛛
	'monster/s5_web.groovy',//  昆 
	'monster/sb5_web.groovy',//  目令昆 
	'monster/35_armoredbettle.groovy',// 重甲蝎兽
	'monster/36_buma.groovy',// 布玛熊
	'monster/37_bronzewolverine.groovy',// 铜狼
	'monster/37_skeletonarcher.groovy',// 骷髅射手
	'monster/38_crypt.groovy',// 地精
	'monster/38_silverwolverine.groovy',// 银狼
	'monster/40_bargon.groovy',// 刀斧手
	'monster/40_crypt.groovy',// 农赋飘2
	'monster/a1-bargon.groovy',// 绿色刀斧
	'monster/b_33_bargon.groovy',// 超级刀斧手
	'monster/s4_bargon.groovy',//  官帮 
	'monster/sb4_bargon.groovy',//  官快沛 
	'monster/41_goldenwolverine.groovy',// 金狼
	'monster/a1-goldenwolverine.groovy',// 黄金狼
	'monster/43_mightygoblin.groovy',// 魔兽怪
	'monster/b_43_mightygoblin.groovy',// 超级魔兽怪
	'monster/44_skeletonranger.groovy',// 骷髅游骑兵
	'monster/b_44_skeletonranger.groovy',// 超级骷髅游骑兵
	'monster/47_cyclopsknight.groovy',// 独眼魔神
	'monster/46_hungky.groovy',// 请虐
	'monster/48_hungky.groovy',// 小绿人
	'monster/49_skeletonwarrior.groovy',// 骷髅战士
	'monster/49_vampiricbat.groovy',// 独眼蝙蝠
	'monster/50_evilsnail.groovy',// 蜗牛怪
	'monster/50_greven.groovy',// 巨蜥怪
	'monster/50_guardhopy.groovy',// 独角守护者
	'monster/50_santagoblin-b.groovy',// 大圣诞精灵
	'monster/a1-greven.groovy',// 绿蜥怪
	'monster/52_direbee.groovy',// 蜜蜂精
	'monster/52_muffin.groovy',// 松饼怪
	'monster/53_titan.groovy',// 泰坦巨人
	'monster/a2-titan.groovy',// 泰坦魔人
	'monster/b_53_titan.groovy',// 超级泰坦巨人
	'monster/54_mudygolem.groovy',// 泥妖
	'monster/54_skeletonknight.groovy',// 骷髅爵士
	'monster/b_54_skeletonknight.groovy',// 超级骷髅骑士
	'monster/55_sandlem.groovy',// 沙妖
	'monster/65_darkknight.groovy',// 黑暗骑士
	'monster/a2-sandlem.groovy',// 黄沙妖
	'monster/56_avelisk-s.groovy',// 魔剑人马
	'monster/57_mirekeeper.groovy',// 泥潭守护者
	'monster/58_evilmaple.groovy',// 黑暗枫树
	'monster/59_headcutter.groovy',// 魔剑士
	'monster/b_59_headcutter 1.groovy',// 超级魔剑士
	'monster/b_59_headcutter 2.groovy',// 超级魔斗士
	'monster/s6_headcutter.groovy',//  庆靛目磐 
	'monster/sb6_headcutter.groovy',//  海啊 靛固福 
	'monster/00_santagoblin-c.groovy',// 圣诞精灵
	'monster/60_death_night.groovy',// 暗夜骑士
	'monster/60_evilplant.groovy',// 黑暗魔树
	'monster/60_solidsnail.groovy',// 变种蜗牛
	'monster/60_s_fireelemental.groovy',// 火灵神
	'monster/60_s_wolverin.groovy',// 雪狼
	'monster/60_towergolem.groovy',// 巨塔石人
	'monster/a2-fireelemental.groovy',// 火焰元素
	'monster/61_avelisk-l.groovy',// 魔枪人马
	'monster/62_beevil.groovy',// 蜂王
	'monster/62_thorncrawler.groovy',// 荆棘爬行者
	'monster/64_mummy.groovy',// 木乃伊
	'monster/a1-mummy.groovy',// 缠布尸
	'monster/66_slaughter.groovy',// 魔剑圣
	'monster/b_66_slaughter.groovy',// 超级魔剑圣
	'monster/67_illusionknight.groovy',// 魔战妖王
	'monster/67_nightmare.groovy',// 梦魇
	'monster/a3-nightmare.groovy',// 吸魂妖
	'monster/b_67_illusionknight.groovy',// 超级魔战妖王
	'monster/68_aveliskqueen.groovy',// 魔弓手
	'monster/69_doomguard.groovy',// 黑暗爵士
	'monster/69_figon.groovy',// 火灵王
	'monster/69_naz.groovy',// 夜行者
	'monster/a3-figon.groovy',// 火灵魔王
	'monster/b_69_figon.groovy',// 超级火灵王
	'monster/s7_figon.groovy',//  颇捞帮 
	'monster/sb7_figon.groovy',//  秋教 
	'monster/70_avelisklord.groovy',// 魔锤人马
	'monster/70_santagoblin-a.groovy',// 巨大圣诞精灵
	'monster/70_s_metalgolem.groovy',// 终极机械
	'monster/71_witch.groovy',// 女巫
	'monster/a4-witch.groovy',// 生化女巫
	'monster/72_great_greven.groovy',// 铁甲巨蜥
	'monster/72_heavygoblin.groovy',// 重装魔兽兵
	'monster/72_sliver.groovy',// 三角魔神
	'monster/73_m_stonegiant.groovy',// 小无双石怪
	'monster/73_omu.groovy',// 变异甲虫
	'monster/73_stonegiant.groovy',// 无双石怪
	'monster/b_73_stonegiant.groovy',// 超级无双石怪
	'monster/74_stonegolem.groovy',// 无双石魔
	'monster/75_beetle.groovy',// 独眼甲虫
	'monster/75_dusk.groovy',// 达克
	'monster/75_hulk.groovy',// 绿巨人
	'monster/75_succubus.groovy',// 萨酷巴斯
	'monster/a2-dusk.groovy',// 达斯克
	'monster/a3-hulk.groovy',// 浩克
	'monster/qsr.groovy',// 小魔怪
	'monster/qsr2.groovy',// 　小魔怪　
	'monster/soldier_a.groovy',// 卫兵
	'monster/76_stingray.groovy',// 毒眼飞蛾
	'monster/s9_hulk.groovy',//  擎农 
	'monster/sb9_hulk.groovy',//  鸥捞乾 
	'monster/77_dawlin.groovy',// 双头独眼
	'monster/79_aveliskqueen.groovy',// 魔弓女王
	'monster/79_m_lord.groovy',// 木乃伊旗主
	'monster/79_omicron.groovy',// 坷固农沸
	'monster/79_shadow.groovy',// 鬼影杀手
	'monster/79_stygian.groovy',// 幽灵
	'monster/a3-omicron.groovy',// Ω
	'monster/80_deadhopy.groovy',// 无息独角兽
	'monster/80_guardian.groovy',// 守护圣徒
	'monster/80_lizardfolk.groovy',// 嗜血屠狼
	'monster/80_magicmaster.groovy',// 魔法导师
	'monster/80_skillmaster.groovy',// 技能导师
	'monster/86_grotesque.groovy',// 弊肺抛胶农
	'monster/a1z-buma.groovy',// 杀戮者
	'monster/s51_guardian.groovy',// 啊叼救 技牢飘
	'monster/81_ironguard.groovy',// 铁甲狂魔
	'monster/a4-ironguard.groovy',// 机械守卫
	'monster/s11_ironguard.groovy',//  酒捞攫 啊靛 
	'monster/sb11_ironguard.groovy',//  捞固萍福 啊靛 
	'monster/82_avelin.groovy',// 魔弓人马
	'monster/82_incubus.groovy',// 英酷巴斯
	'monster/82_strider.groovy',// 双刀娜迦
	'monster/a8-hellhound.groovy',// 木星犬
	'monster/v1_darkmage.groovy',// DarkMage
	'monster/v1_hellhound.groovy',// Hellhound
	'monster/83_arcuda.groovy',// 笨笨熊
	'monster/83_avelinqueen.groovy',// 人马女皇
	'monster/83_chaingolem.groovy',// 链锤傀儡
	'monster/83_omicron.groovy',// 神秘十五
	'monster/v1_fireworm.groovy',// Fireworm
	'monster/84_berserker.groovy',// 狂暴战士
	'monster/84_hypermachine.groovy',// 杀戮机械
	'monster/84_rampage.groovy',// 暴跳怪
	'monster/a5-rampage.groovy',// 机械战蜥
	'monster/v1_bloodyknight.groovy',// BloodyKnight
	'monster/v1_darkguard.groovy',// Skullac
	'monster/85_deadzone.groovy',// 机械魔蚊
	'monster/85_spider.groovy',// 蜘蛛女皇
	'monster/85_stygian.groovy',// 幽灵之主
	'monster/85_typhoon.groovy',// 台风
	'monster/85_vampiricbee.groovy',// 嗜血蜂
	'monster/85_vampiricmachine.groovy',// 嗜血机械
	'monster/a4-deadzone.groovy',// 机械杀手
	'monster/a4-typhoon.groovy',// 飓风战士
	'monster/s60_stygianlord.groovy',// 胶萍瘤攫 肺靛
	'monster/v2_threetoes.groovy',// ThreeToes
	'monster/86_kinghopy.groovy',// 独角兽王
	'monster/b_86_kinghopy.groovy',// 超级独角兽王
	'monster/sb8_kinghopy.groovy',//  龋矾乔柯 
	'monster/v1_darkphalanx.groovy',// Dark Phalanx
	'monster/v2_templeguard.groovy',// TempleGuard
	'monster/87_darkspecter.groovy',// 鬼影魔神
	'monster/87_morgon.groovy',// 巨斧萨满
	'monster/87_runicguardian.groovy',// 远古守卫
	'monster/a5-morgon.groovy',// 巨斧战士
	'monster/s10_darkspecter.groovy',//  促农 胶棋磐 
	'monster/sb10_darkspecter.groovy',//  促农 埔乓 
	'monster/v2_kingspider.groovy',// KingSpider
	'monster/88_metron.groovy',// 异形
	'monster/88_mystic.groovy',// 神秘尖晶石
	'monster/88_sadness.groovy',// 机械刑天
	'monster/92_omega.groovy',// 神秘十八
	'monster/soldier_b.groovy',// 警卫兵
	'monster/soldier_d.groovy',// 护卫兵
	'monster/v2_deathmage.groovy',// DeathMage
	'monster/89_d-machine.groovy',// 霸天蛛
	'monster/89_mountain.groovy',// 巨锤魔
	'monster/a5-d-machine.groovy',// 代号(D)
	'monster/b_89_stygianlord.groovy',// 超级幽灵
	'monster/90_demon.groovy',// 魔鬼
	'monster/a6-darkguard.groovy',// 迷失弓魔
	'monster/a6-templeguard.groovy',// 坦普
	'monster/x1_darkwitchrpt.groovy',// DarkwitchRPT
	'monster/x1_hobogolem.groovy',// hobogolem
	'monster/x1_rptshurikar.groovy',// RPTshurikar
	'monster/91_coldeye.groovy',// 冷眼魔
	'monster/91_runicguardian.groovy',// 远古祭司
	'monster/b_91_runicguardian.groovy',// 超级远古祭司
	'monster/92_frozen.groovy',// 冰妖
	'monster/a5-ironfist.groovy',// 银甲魔人
	'monster/a6-deadkinghopy.groovy',// 黑暗兽王
	'monster/a6-gorgon.groovy',// 堕落战神
	'monster/x1_deadkinghopy.groovy',// Deadkinghopy
	'monster/x1_gorgon.groovy',// gorgon
	'monster/93_icegoblin.groovy',// 冰甲魔兽兵
	'monster/94_frost.groovy',// 寒霜魔
	'monster/95_icegolem.groovy',// 冰石人
	'monster/hpt1_armoredbettle.groovy',// 地耀怪
	'monster/hpt1_bomicron.groovy',// 欧米加战神
	'monster/hpt1_fireelemental.groovy',// 诅咒之焰
	'monster/hpt1_newmon.groovy',// 维尼斯
	'monster/hpt1_silverwolverine.groovy',// 魔狼
	'monster/hpt1_woniu.groovy',// 幽灵水怪
	'monster/x2_ar.groovy',// d_ar
	'monster/x2_atal.groovy',// d_atal
	'monster/x2_fi.groovy',// d_fi
	'monster/x2_kn.groovy',// d_kn
	'monster/x2_magi.groovy',// d_magi
	'monster/x2_meca.groovy',// d_meca
	'monster/x2_pa.groovy',// d_pa
	'monster/x2_pr.groovy',// d_pr
	'monster/96_cyclopswarrior.groovy',// 冰甲独眼
	'monster/97_turtlecannon.groovy',// 霸天龟
	'monster/98_incubussummer.groovy',// 冰风女妖
	'monster/99_blizzardgiant.groovy',// 冰甲无双
	'monster/99_fireworm.groovy',// 火烈树
	'monster/99_orbit.groovy',// 眼怪魔
	'monster/100_chaoscara.groovy',// 卡奥斯
	'monster/100_chimera.groovy',// 龙鹰灵兽
	'monster/100_devilbird.groovy',// 冰风魔王
	'monster/100_evilspirit.groovy',// 邪恶火灵
	'monster/100_grotesque.groovy',// 亚特兰斯巨人
	'monster/100_hellhound.groovy',// 地狱猎犬
	'monster/100_ironfist.groovy',// 铁拳
	'monster/100_ratoo.groovy',// 鲁图怪
	'monster/88_ironfist.groovy',// 酒捞攫 乔胶飘
	'monster/a3z-kingspider.groovy',// 蜘蛛王
	'monster/a7-mystic.groovy',// 暴躁的冰块
	'monster/b100_doomlord.groovy',// 超级黑暗爵士
	'monster/b_100_monclip.groovy',// 超级地精
	'monster/b_100_ratoolord.groovy',// 超级鲁图怪王
	'monster/b_80_lizardfolk.groovy',// 超级嗜血屠狼
	'monster/event_cstone.groovy',// 守护水晶
	'monster/event_evilspirit.groovy',// 邪恶火灵
	'monster/event_hestian.groovy',// 烈火麒麟
	'monster/ha_death_knight.groovy',// 幽灵骑士
	'monster/ha_decoy.groovy',// 神秘布娃娃
	'monster/ha_illusionknight.groovy',// 魔战妖灵
	'monster/ha_leech.groovy',// 梦魇毒蛇
	'monster/ha_magicmaster.groovy',// 神秘魔导
	'monster/ha_monclip-boss.groovy',// 神秘地之精灵
	'monster/ha_mystic.groovy',// 魔冰
	'monster/ha_ratoo.groovy',// 神秘领主
	'monster/s1_hopy.groovy',//  龋乔 
	'monster/s8_kinghopy.groovy',//  欧龋乔 
	'monster/soldier_c.groovy',// 禁卫兵
	'monster/vip_bargon.groovy',// 刀斧战士
	'monster/vip_beetle.groovy',// 厚撇
	'monster/vip_figon.groovy',// 火灵战士
	'monster/vip_fireelemental.groovy',// 火灵斗士
	'monster/vip_greven.groovy',// 沙漠绿蜥
	'monster/vip_muffin.groovy',// 木蘑头
	'monster/z1chaos.groovy',// 黑暗天使
	'monster/101_chaoscara.groovy',// 命运女神
	'monster/101_darkguard.groovy',// 神弓魔
	'monster/102_darkmage.groovy',// 暗月法师
	'monster/102_darkphalanx.groovy',// 破日魔王
	'monster/s2ireworm.groovy',// 龙炎树
	'monster/103_bloodyknight.groovy',// 嗜血骑士
	'monster/s2ightmare.groovy',// 梦魇
	'monster/s2owergolem.groovy',// 机械战塔
	'monster/s2usk.groovy',// 达克魔王
	'monster/a7-deathmage.groovy',// 教皇
	'monster/b_104_babel.groovy',// 巴别塔
	'monster/b_104_babel2.groovy',// 巴别塔(改)
	'monster/b_104_babel3.groovy',// 巴别塔(真)
	'monster/s2eathmage.groovy',// 黑暗教皇
	'monster/105_kingspider.groovy',// 红岭蛛王
	'monster/105_seto.groovy',// 暗凰冤魂
	'monster/s2orgon.groovy',// 死亡使者
	'monster/106_templeguard.groovy',// 坦普守护者
	'monster/a7-darkmage.groovy',// 地狱傀儡
	'monster/110_death_knight.groovy',// 死亡骑士
	'monster/110_fury.groovy',// 狮面魔王
	'monster/110_hobogolem.groovy',// 无息魔王
	'monster/110_kelvezu.groovy',// 凯尔维苏
	'monster/a5z-chimera.groovy',// 依美拉
	'monster/a7-coldeye.groovy',// 酷冷之眼
	'monster/vip_mummy.groovy',// 沙漠木乃伊
	'monster/z4bob.groovy',// 金焰凤凰
	'monster/z4boby.groovy',// 　金焰凤凰　
	'monster/z5kelvezu.groovy',// 魔龙
	'monster/z5kelvezuy.groovy',// 小魔龙
	'monster/111_deadkinghopy.groovy',// 无息兽王
	'monster/111_fury.groovy',// 命运之主
	'monster/a8-buma.groovy',// 黑暗杀戮者
	'monster/a8-threetoes.groovy',// 远古树妖
	'monster/a8-figon.groovy',// 血焰王
	'monster/a7z-magicmaster.groovy',// 幽暗魔导
	'monster/u1_chaoscara.groovy',// 叛变雪天使
	'monster/u1_frost.groovy',// 雪域守护者
	'monster/u1_frozen.groovy',// 雪域浮灵
	'monster/u1_frozewr.groovy',// 雪之焰
	'monster/u1_icegoblin.groovy',// 雪域魔兽
	'monster/u1_icegolem.groovy',// 幽拉战士
	'monster/116_ratoolord.groovy',// 鲁图王
	'monster/u2_blizzardgiant.groovy',// 无双冰魔
	'monster/u2_cyclopswarrior.groovy',// 雪域魔神
	'monster/u2_devilbird.groovy',// 幽拉
	'monster/u2_incubussummer.groovy',// 死月魔女
	'monster/u2_turtlecannon.groovy',// 重甲魔战龟
	'monster/118_fury2.groovy',// 狮面魔王(改)
	'monster/119_fury3.groovy',//  狮面魔王(极)
	'monster/119_mimic.groovy',// 怪物箱子
	'monster/a8z-kelvezu.groovy',// 守护魔龙
	'monster/dy_buma.groovy',// 地狱杀戮者
	'monster/dy_chimera.groovy',// 绮美拉
	'monster/dy_figon.groovy',// 血灵王
	'monster/dy_fury.groovy',// 地狱狮皇
	'monster/dy_prince.groovy',// 魔剑战神
	'monster/tt_avelinqueen.groovy',// 人马皇后
	'monster/tt_illusionknight.groovy',// 米兰达
	'monster/tt_kinghopy.groovy',// 兽王之魂
	'monster/tt_metalgolem.groovy',// 装甲战神
	'monster/tt_wolverin.groovy',// 雪狼
	'monster/120_fury4.groovy',// 狮面魔王(真)
	'monster/120_mokova.groovy',// 暗夜死灵
	'monster/bal_crystal.groovy',// 瓦尔哈拉之塔
	'monster/castledoor.groovy',// 城门
	'monster/t_crystal_b.groovy',// 冰水晶塔
	'monster/t_crystal_g.groovy',// 雷水晶塔
	'monster/t_crystal_n.groovy',// 水晶塔
	'monster/t_crystal_r.groovy',// 火水晶塔
	'monster/z21_fireelemental.groovy',// 幻化之焰
	'monster/121_niken.groovy',// 尼肯
	'monster/122_kingbat.groovy',// 吸血蝙蝠
	'monster/124_goblinshaman.groovy',// 魔法魔兽兵
	'monster/124_iceworm.groovy',// 寒冰树
	'monster/124_minebat.groovy',// 寒冰恶魔
	'monster/107_d_ar.groovy',// 箭神
	'monster/107_d_atal.groovy',// 女武神
	'monster/107_d_fi.groovy',// 圣殿武士
	'monster/107_d_kn.groovy',// 剑圣
	'monster/107_d_magi.groovy',// 黑魔导师
	'monster/107_d_meca.groovy',// 机甲武士
	'monster/107_d_pa.groovy',// 皇家骑士
	'monster/107_d_pr.groovy',// 圣灵法师
	'monster/116_gorgon.groovy',// 米诺陶斯
	'monster/125_kakoa.groovy',// 卡卡噢
	'monster/125_minegolem.groovy',// 矿山机械
	'monster/128_morgonia.groovy',// 巨斧守卫
	'monster/sl1_arma.groovy',// 甲壳鼠
	'monster/sl1_hobgoblin.groovy',// 树林魔怪
	'monster/sl1_hopy.groovy',// 小独角兽
	'monster/sl1_mudy.groovy',// 泥巴精
	'monster/sl1_mush.groovy',// 小毒蘑菇
	'monster/sl1_mushroomghost.groovy',// 小蘑菇
	'monster/sl1_rabie.groovy',// 大耳兔妖
	'monster/126_sealcrasher.groovy',// 矿山晶石
	'monster/126_tarantulika.groovy',// 冰甲毒蛛
	'monster/127_hest.groovy',// 奥兹
	'monster/127_nazsenior.groovy',// 纳兹
	'monster/127_undeadmanager.groovy',// 矿山管理者
	'monster/128_hound.groovy',// 地狱犬
	'monster/128_iceserpent.groovy',// 海龙
	'monster/128_ruca.groovy',// 幽灵之主
	'monster/128_turtledragon.groovy',// 霸天龟王
	'monster/128_undeadminer.groovy',// 矿山开采者
	'monster/128_undeadstalker.groovy',// 死亡巫师
	'monster/129_sprin.groovy',// 斯普林
	'monster/130_devilshy.groovy',// 双子恶魔
	'monster/130_itechnician.groovy',// 技师侵略者
	'monster/131_igolation.groovy',// 死神
	'monster/131_ltechnician.groovy',// 研究所技师
	'monster/131_undeadmaple.groovy',// 死亡枫树
	'monster/132_lengineer.groovy',// 研究所工程师
	'monster/133_isoldier.groovy',// 渗透侵略者
	'monster/133_xetan.groovy',// 氙谭
	'monster/127_tulla.groovy',// 恶魔伯爵
	'monster/135_ibomber.groovy',// 爆破侵略者
	'monster/128_lena.groovy',// 雷娜
	'monster/128_marionette.groovy',// 吊死鬼
	'monster/136_billy.groovy',// 比利
	'monster/136_lguardian.groovy',// 研究所装甲兵
	'monster/128_redeye.groovy',// 火眼魔
	'monster/138_ielite.groovy',// 精兵侵略者
	'monster/128_billys.groovy',// 狂暴比利
	'monster/128_lenas.groovy',// 狂暴雷娜
	'monster/128_marionettes.groovy',// 狂暴吊死鬼
	'monster/128_undeadstalkers.groovy',// 狂暴死亡巫师
	'monster/140_draxos.groovy',// 埃克斯
	'monster/sl2_doral.groovy',// 跳虫
	'monster/sl2_egan.groovy',// 精灵帽
	'monster/sl2_minig.groovy',// 豆糕人
	'monster/sl2_northgoblin.groovy',// 栖息地魔怪
	'monster/sl2_orbit.groovy',// 飓风眼
	'monster/sl2_sen.groovy',// 林间眩晕灯
	'monster/rpt_thecolossi1.groovy',// 夜魔族骑士★☆
	'monster/rpt_thecolossi2.groovy',// 夜魔族骑士★★
	'monster/rpt_thecolossi3.groovy',// 夜魔族骑士★★☆
	'monster/rpt_thecolossi4.groovy',// 夜魔族骑士★★★
	'monster/rpt_thecolossi5.groovy',// 夜魔族骑士★★★☆
	'monster/rpt_thecolossi6.groovy',// 夜魔族骑士★★★★
	'monster/z2fury.groovy',// 幽灵狮魔
	'monster/yizardfolk.groovy',// 雪狼精
	'monster/ymu.groovy',// 幽绿毒虫
	'monster/sl3_beedog.groovy',// 变种蜂巢
	'monster/sl3_devilishtree.groovy',// 树魔人
	'monster/sl3_hauntingmaple.groovy',// 老树妖
	'monster/sl3_mephit.groovy',// 水精灵
	'monster/sl3_minigsilver.groovy',// 水豆糕
	'monster/sl3_mutantrabie.groovy',// 长腿兔
	'monster/ycoldeye.groovy',// 影精灵
	'monster/ystrider.groovy',// 卡塔尔海妖
	'monster/yreven.groovy',// 鬼蜥王
	'monster/yspider.groovy',// 小幻影蛛王
	'monster/ystingray.groovy',// 瀑雪龙鱼
	'monster/gmt.groovy'// 寒冰鬼眼
]
