-- Auto-converted from server\mssql\GameDB.sql
-- 请在测试环境中验证类型、约束和序列设置是否符合预期。




CREATE TABLE AchievementList(
	id char(10) NULL
);
CREATE TABLE ActionFieldSettings(
	id char(10) NULL
);
CREATE TABLE AgeList(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	AgeNumber integer NOT NULL,
	FailChance integer NOT NULL,
	Plus2Chance integer NOT NULL,
	Minus2Chance integer NOT NULL,
	Minus1Chance integer NOT NULL,
	BrokenChance integer NOT NULL,
	AgeStone integer NOT NULL,
 CONSTRAINT PK_AgeList PRIMARY KEY(ID));
CREATE TABLE BaselineMod(
	Class integer NOT NULL,
	PercentBaselineStrength integer NOT NULL,
	PercentBaselineSpirit integer NOT NULL,
	PercentBaselineTalent integer NOT NULL,
	PercentBaselineAgility integer NOT NULL,
	PercentBaselineHealth integer NOT NULL,
 CONSTRAINT PK_BaselineMod PRIMARY KEY 
(
	Class 
)
);
CREATE TABLE CharacterClass(
	ID integer NOT NULL,
	ID2 integer NOT NULL,
	Name varchar(32) NOT NULL,
	ShortName varchar(8) NOT NULL
);
CREATE TABLE cheatExceptionList(
	exceptionName varchar(100) NULL,
	id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
PRIMARY KEY(ID));
CREATE TABLE CheatList(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	CheatType integer NOT NULL,
	CheatID integer NOT NULL,
	CheatName varchar(64) NOT NULL,
	CheatSignature integer NOT NULL,
 CONSTRAINT PK_CheatList PRIMARY KEY(ID));
CREATE TABLE CheatModules(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	ModuleName varchar(64) NOT NULL,
 CONSTRAINT PK_CheatModules PRIMARY KEY(ID));
CREATE TABLE CoinShop(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	Name varchar(32) NOT NULL,
	Message varchar(128) NOT NULL,
	Discount integer NOT NULL,
	Active integer NOT NULL,
 CONSTRAINT PK_CoinShop PRIMARY KEY(ID));
CREATE TABLE CoinShopItem(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	TabID integer NOT NULL,
	Name varchar(32) NOT NULL,
	Description varchar(128) NOT NULL,
	Code varchar(8) NOT NULL,
	Image varchar(64) NOT NULL,
	Value integer NOT NULL,
	Discount integer NOT NULL,
	Bulk integer NOT NULL,
	MaxBulk integer NOT NULL,
	IsSpec integer NOT NULL,
	IsQuantity integer NOT NULL,
	Disabled integer NOT NULL,
	ListOrder integer NOT NULL,
 CONSTRAINT PK_CoinShopItem PRIMARY KEY(ID));
CREATE TABLE CoinShopTab(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	CoinShopID integer NOT NULL,
	Name varchar(32) NOT NULL,
	ParentID integer NOT NULL,
	Discount integer NOT NULL,
	Bulk integer NOT NULL,
	MaxBulk integer NOT NULL,
	ListOrder integer NOT NULL,
 CONSTRAINT PK_CoinShopTab PRIMARY KEY(ID));
CREATE TABLE DropItem(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	DropID integer NOT NULL,
	Items varchar(512) NOT NULL,
	Chance integer NOT NULL,
	GoldMin integer NOT NULL,
	GoldMax integer NOT NULL,
 CONSTRAINT PK_DropItem PRIMARY KEY(ID));
CREATE TABLE ItemAttribute(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	Code integer NOT NULL,
	Name varchar(32) NOT NULL,
	BeforeValue varchar(16) NULL,
	AfterValue varchar(16) NULL,
	BeforeValueSpec varchar(16) NULL,
	AfterValueSpec varchar(16) NULL,
 CONSTRAINT PK_ItemAttribute PRIMARY KEY(ID));
CREATE TABLE ItemCode(
	Code integer NOT NULL,
	Text varchar(16) NOT NULL,
 CONSTRAINT PK_ItemCode PRIMARY KEY 
(
	Code 
)
);
CREATE TABLE ItemFixes(
	id integer NOT NULL,
	Name varchar(12) NOT NULL,
	MinLevel integer NOT NULL,
	MaxLevel integer NOT NULL,
	MinRarity integer NOT NULL,
	MaxRarity integer NOT NULL,
	isPrefix integer NOT NULL,
	isSuffix integer NOT NULL,
	Chance integer NOT NULL,
	Axes integer NOT NULL,
	Bows integer NOT NULL,
	Javelins integer NOT NULL,
	Daggers integer NOT NULL,
	Wands integer NOT NULL,
	Scythes integer NOT NULL,
	Swords integer NOT NULL,
	Claws integer NOT NULL,
	Hammers integer NOT NULL,
	Phantoms integer NOT NULL,
	Armors integer NOT NULL,
	Robes integer NOT NULL,
	Boots integer NOT NULL,
	Gauntlets integer NOT NULL,
	Bracelets integer NOT NULL,
	Amulets integer NOT NULL,
	Rings integer NOT NULL,
	Shields integer NOT NULL,
	Orbs integer NOT NULL,
	OrganicMin integer NOT NULL,
	OrganicMax integer NOT NULL,
	FireMin integer NOT NULL,
	FireMax integer NOT NULL,
	FrostMin integer NOT NULL,
	FrostMax integer NOT NULL,
	LightningMix integer NOT NULL,
	LightningMax integer NOT NULL,
	PoisonMin integer NOT NULL,
	PoisonMax integer NOT NULL,
	ATKPowMin integer NOT NULL,
	ATKPowMax integer NOT NULL,
	RangeMin integer NOT NULL,
	RangeMax integer NOT NULL,
	ATKRatingMin integer NOT NULL,
	ATKRatingMax integer NOT NULL,
	CriticalMin real NOT NULL,
	CriticalMax real NOT NULL,
	BlockMin real NOT NULL,
	BlockMax real NOT NULL,
	AbsorbMin real NOT NULL,
	AbsorbMax real NOT NULL,
	DefenseMin integer NOT NULL,
	DefenseMax integer NOT NULL,
	RegenerationHPMin real NOT NULL,
	RegenerationHPMax real NOT NULL,
	RegenerationMPMin real NOT NULL,
	RegenerationMPMax real NOT NULL,
	AddHPMin integer NOT NULL,
	AddHPMax integer NOT NULL,
	AddMPMin integer NOT NULL,
	AddMPMax integer NOT NULL,
	RunSpeedMin real NOT NULL,
	RunSpeedMax real NOT NULL,
 CONSTRAINT PK_ItemFixes PRIMARY KEY(ID));
CREATE TABLE ItemList(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	IDCode integer NOT NULL,
	Name varchar(50) NOT NULL,
	nullcode varchar(50) NOT NULL,
	CodeIMG1 varchar(50) NOT NULL,
	CodeIMG2 varchar(50) NOT NULL,
	Width integer NOT NULL,
	Height integer NOT NULL,
	DropFolder varchar(50) NOT NULL,
	ClassItem integer NOT NULL,
	ModelPosition integer NOT NULL,
	Sound integer NOT NULL,
	WeaponClass integer NOT NULL,
	QuestID integer NOT NULL,
	QuestR integer NOT NULL,
	QuestG integer NOT NULL,
	QuestB integer NOT NULL,
	QuestTransparency integer NOT NULL,
	QuestFlashingTime integer NOT NULL,
	ReqLevel integer NOT NULL,
	ReqStrengh integer NOT NULL,
	ReqSpirit integer NOT NULL,
	ReqTalent integer NOT NULL,
	ReqAgility integer NOT NULL,
	ReqHealth integer NOT NULL,
	IntegrityMin integer NOT NULL,
	IntegrityMax integer NOT NULL,
	Weight integer NOT NULL,
	Price integer NOT NULL,
	OrganicMin integer NOT NULL,
	OrganicMax integer NOT NULL,
	FireMin integer NOT NULL,
	FireMax integer NOT NULL,
	FrostMin integer NOT NULL,
	FrostMax integer NOT NULL,
	LightningMix integer NOT NULL,
	LightningMax integer NOT NULL,
	PoisonMin integer NOT NULL,
	PoisonMax integer NOT NULL,
	ATKPow1Min integer NOT NULL,
	ATKPow1Max integer NOT NULL,
	ATKPow2Min integer NOT NULL,
	ATKPow2Max integer NOT NULL,
	Range integer NOT NULL,
	ATKSpeed integer NOT NULL,
	ATKRatingMin integer NOT NULL,
	ATKRatingMax integer NOT NULL,
	Critical integer NOT NULL,
	BlockMin real NOT NULL,
	BlockMax real NOT NULL,
	AbsorbMin real NOT NULL,
	AbsorbMax real NOT NULL,
	DefenseMin integer NOT NULL,
	DefenseMax integer NOT NULL,
	PotionSpace integer NOT NULL,
	PotionCount integer NOT NULL,
	RegenerationHPMin real NOT NULL,
	RegenerationHPMax real NOT NULL,
	RegenerationMPMin real NOT NULL,
	RegenerationMPMax real NOT NULL,
	RegenerationSTMMin real NOT NULL,
	RegenerationSTMMax real NOT NULL,
	AddHPMin integer NOT NULL,
	AddHPMax integer NOT NULL,
	AddMPMin integer NOT NULL,
	AddMPMax integer NOT NULL,
	AddSTMMin integer NOT NULL,
	AddSTMMax integer NOT NULL,
	RecoveryHPMin integer NOT NULL,
	RecoveryHPMax integer NOT NULL,
	RecoveryMPMin integer NOT NULL,
	RecoveryMPMax integer NOT NULL,
	RecoverySTMMin integer NOT NULL,
	RecoverySTMMax integer NOT NULL,
	RunSpeedMin real NOT NULL,
	RunSpeedMax real NOT NULL,
	PrimarySpec integer NOT NULL,
	AddSpecClass1 integer NOT NULL,
	AddSpecClass2 integer NOT NULL,
	AddSpecClass3 integer NOT NULL,
	AddSpecClass4 integer NOT NULL,
	AddSpecClass5 integer NOT NULL,
	AddSpecClass6 integer NOT NULL,
	AddSpecClass7 integer NOT NULL,
	AddSpecClass8 integer NOT NULL,
	AddSpecClass9 integer NOT NULL,
	AddSpecClass10 integer NOT NULL,
	AddSpecClass11 integer NOT NULL,
	AddSpecClass12 integer NOT NULL,
	AddSpecRunSpeedMin real NOT NULL,
	AddSpecRunSpeedMax real NOT NULL,
	AddSpecAbsorbMin real NOT NULL,
	AddSpecAbsorbMax real NOT NULL,
	AddSpecDefenseMin integer NOT NULL,
	AddSpecDefenseMax integer NOT NULL,
	AddSpecAtkSpeed integer NOT NULL,
	AddSpecCritical integer NOT NULL,
	AddSpecAtkPowerMin integer NOT NULL,
	AddSpecAtkPowerMax integer NOT NULL,
	AddSpecAtkRatingMin integer NOT NULL,
	AddSpecAtkRatingMax integer NOT NULL,
	AddSpecHPRegen real NOT NULL,
	AddSpecMPRegenMin real NOT NULL,
	AddSpecMPRegenMax real NOT NULL,
	AddSpecSTMRegen real NOT NULL,
	AddSpecBlock real NOT NULL,
	AddSpecRange integer NOT NULL,
	CannotDrop integer NOT NULL,
 CONSTRAINT PK_ItemList PRIMARY KEY(ID));
CREATE TABLE ItemListOld(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	IDCode integer NOT NULL,
	Name varchar(50) NOT NULL,
	nullcode varchar(50) NOT NULL,
	CodeIMG1 varchar(50) NOT NULL,
	CodeIMG2 varchar(50) NOT NULL,
	Width integer NOT NULL,
	Height integer NOT NULL,
	DropFolder varchar(50) NOT NULL,
	ClassItem integer NOT NULL,
	ModelPosition integer NOT NULL,
	Sound integer NOT NULL,
	WeaponClass integer NOT NULL,
	QuestID integer NOT NULL,
	QuestR integer NOT NULL,
	QuestG integer NOT NULL,
	QuestB integer NOT NULL,
	QuestTransparency integer NOT NULL,
	QuestFlashingTime integer NOT NULL,
	ReqLevel integer NOT NULL,
	ReqStrengh integer NOT NULL,
	ReqSpirit integer NOT NULL,
	ReqTalent integer NOT NULL,
	ReqAgility integer NOT NULL,
	ReqHealth integer NOT NULL,
	IntegrityMin integer NOT NULL,
	IntegrityMax integer NOT NULL,
	Weight integer NOT NULL,
	Price integer NOT NULL,
	OrganicMin integer NOT NULL,
	OrganicMax integer NOT NULL,
	FireMin integer NOT NULL,
	FireMax integer NOT NULL,
	FrostMin integer NOT NULL,
	FrostMax integer NOT NULL,
	LightningMix integer NOT NULL,
	LightningMax integer NOT NULL,
	PoisonMin integer NOT NULL,
	PoisonMax integer NOT NULL,
	ATKPow1Min integer NOT NULL,
	ATKPow1Max integer NOT NULL,
	ATKPow2Min integer NOT NULL,
	ATKPow2Max integer NOT NULL,
	Range integer NOT NULL,
	ATKSpeed integer NOT NULL,
	ATKRatingMin integer NOT NULL,
	ATKRatingMax integer NOT NULL,
	Critical integer NOT NULL,
	BlockMin real NOT NULL,
	BlockMax real NOT NULL,
	AbsorbMin real NOT NULL,
	AbsorbMax real NOT NULL,
	DefenseMin integer NOT NULL,
	DefenseMax integer NOT NULL,
	PotionSpace integer NOT NULL,
	PotionCount integer NOT NULL,
	RegenerationHPMin real NOT NULL,
	RegenerationHPMax real NOT NULL,
	RegenerationMPMin real NOT NULL,
	RegenerationMPMax real NOT NULL,
	RegenerationSTMMin real NOT NULL,
	RegenerationSTMMax real NOT NULL,
	AddHPMin integer NOT NULL,
	AddHPMax integer NOT NULL,
	AddMPMin integer NOT NULL,
	AddMPMax integer NOT NULL,
	AddSTMMin integer NOT NULL,
	AddSTMMax integer NOT NULL,
	RecoveryHPMin integer NOT NULL,
	RecoveryHPMax integer NOT NULL,
	RecoveryMPMin integer NOT NULL,
	RecoveryMPMax integer NOT NULL,
	RecoverySTMMin integer NOT NULL,
	RecoverySTMMax integer NOT NULL,
	RunSpeedMin real NOT NULL,
	RunSpeedMax real NOT NULL,
	PrimarySpec integer NOT NULL,
	AddSpecClass1 integer NOT NULL,
	AddSpecClass2 integer NOT NULL,
	AddSpecClass3 integer NOT NULL,
	AddSpecClass4 integer NOT NULL,
	AddSpecClass5 integer NOT NULL,
	AddSpecClass6 integer NOT NULL,
	AddSpecClass7 integer NOT NULL,
	AddSpecClass8 integer NOT NULL,
	AddSpecClass9 integer NOT NULL,
	AddSpecClass10 integer NOT NULL,
	AddSpecClass11 integer NOT NULL,
	AddSpecClass12 integer NOT NULL,
	AddSpecRunSpeedMin real NOT NULL,
	AddSpecRunSpeedMax real NOT NULL,
	AddSpecAbsorbMin real NOT NULL,
	AddSpecAbsorbMax real NOT NULL,
	AddSpecDefenseMin integer NOT NULL,
	AddSpecDefenseMax integer NOT NULL,
	AddSpecAtkSpeed integer NOT NULL,
	AddSpecCritical integer NOT NULL,
	AddSpecAtkPowerMin integer NOT NULL,
	AddSpecAtkPowerMax integer NOT NULL,
	AddSpecAtkRatingMin integer NOT NULL,
	AddSpecAtkRatingMax integer NOT NULL,
	AddSpecHPRegen real NOT NULL,
	AddSpecMPRegenMin real NOT NULL,
	AddSpecMPRegenMax real NOT NULL,
	AddSpecSTMRegen real NOT NULL,
	AddSpecBlock real NOT NULL,
	AddSpecRange integer NOT NULL,
	CannotDrop integer NOT NULL,
 CONSTRAINT PK_ItemListOld PRIMARY KEY(ID));
CREATE TABLE ItemSpec(
	ItemID integer NOT NULL,
	CharacterClassID integer NOT NULL,
	MainSpec integer NOT NULL
);
CREATE TABLE ItemSpecMod(
	AddSpecClass01 integer NOT NULL,
	AddSpecClass02 integer NOT NULL,
	AddSpecClass03 integer NOT NULL,
	AddSpecClass04 integer NOT NULL,
	AddSpecClass05 integer NOT NULL,
	AddSpecClass06 integer NOT NULL,
	AddSpecClass07 integer NOT NULL,
	AddSpecClass08 integer NOT NULL,
	AddSpecClass09 integer NOT NULL,
	AddSpecClass10 integer NOT NULL,
	ItemType varchar(12) NOT NULL,
	PercentReqStrength integer NOT NULL,
	PercentReqSpirit integer NOT NULL,
	PercentReqTalent integer NOT NULL,
	PercentReqAgility integer NOT NULL,
	PercentReqHealth integer NOT NULL,
 CONSTRAINT PK_ItemSpecMod PRIMARY KEY 
(
	AddSpecClass01 
)
);
CREATE TABLE ItemSubType(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	TypeID integer NOT NULL,
	Code integer NOT NULL,
	Name varchar(32) NOT NULL,
 CONSTRAINT PK_ItemSubType PRIMARY KEY(ID));
CREATE TABLE ItemType(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	Code integer NOT NULL,
	Name varchar(32) NOT NULL,
 CONSTRAINT PK_ItemType PRIMARY KEY(ID));
CREATE TABLE ItemValue(
	ItemListID integer NOT NULL,
	AttributeID integer NOT NULL,
	MinValue double precision NOT NULL,
	MaxValue double precision NOT NULL,
	Spec integer NOT NULL
);
CREATE TABLE MapBoss(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	MapID integer NOT NULL,
	BossMonsterID integer NOT NULL,
	MinionMonsterID integer NOT NULL,
	MinionCount integer NOT NULL,
 CONSTRAINT PK_MapBoss PRIMARY KEY(ID));
CREATE TABLE MapBossHour(
	BossID integer NOT NULL,
	Hour integer NOT NULL
);
CREATE TABLE MapIndicator(
	MapID integer NOT NULL,
	Type integer NOT NULL,
	Value integer NOT NULL,
	PosX integer NOT NULL,
	PosZ integer NOT NULL,
	AngleY integer NOT NULL
);
CREATE TABLE MapList(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	Name varchar(50) NULL,
	ShortName varchar(50) NULL,
	TypeMap varchar(50) NULL,
	LevelReq integer NULL,
	Pvp integer NULL,
	StageFile varchar(50) NULL,
 CONSTRAINT PK_MapList PRIMARY KEY(ID));
CREATE TABLE MapMonster(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	Stage varchar(50) NULL,
	MaxMonsters integer NOT NULL,
	Interval integer NOT NULL,
	MaxEnemyFlag integer NOT NULL,
	Monster1 varchar(150) NULL,
	Count1 integer NULL,
	Monster2 varchar(150) NULL,
	Count2 integer NULL,
	Monster3 varchar(150) NULL,
	Count3 integer NULL,
	Monster4 varchar(150) NULL,
	Count4 integer NULL,
	Monster5 varchar(150) NULL,
	Count5 integer NULL,
	Monster6 varchar(150) NULL,
	Count6 integer NULL,
	Monster7 varchar(150) NULL,
	Count7 integer NULL,
	Monster8 varchar(150) NULL,
	Count8 integer NULL,
	Monster9 varchar(150) NULL,
	Count9 integer NULL,
	Monster10 varchar(150) NULL,
	Count10 integer NULL,
	Monster11 varchar(150) NULL,
	Count11 integer NULL,
	Monster12 varchar(150) NULL,
	Count12 integer NULL,
	BossMonster1 varchar(150) NULL,
	HoursBossMonster1 varchar(150) NULL,
	SubMonster1 varchar(150) NULL,
	CountSub1 integer NULL,
	BossMonster2 varchar(150) NULL,
	HoursBossMonster2 varchar(150) NULL,
	SubMonster2 varchar(150) NULL,
	CountSub2 integer NULL,
	BossMonster3 varchar(150) NULL,
	HoursBossMonster3 varchar(150) NULL,
	SubMonster3 varchar(150) NULL,
	CountSub3 integer NULL,
 CONSTRAINT PK_MapMonster PRIMARY KEY(ID));
CREATE TABLE MapNPC(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	Stage integer NOT NULL,
	X integer NOT NULL,
	Y integer NOT NULL,
	Z integer NOT NULL,
	Angle integer NOT NULL,
	IDNPC integer NOT NULL,
	Enabled integer NOT NULL,
	OnlyGM integer NOT NULL,
 CONSTRAINT PK_MapNPC PRIMARY KEY(ID));
CREATE TABLE MapSpawnPoint(
	ID integer NOT NULL,
	Stage integer NULL,
	X integer NULL,
	Z integer NULL,
	Description varchar(150) NULL,
 CONSTRAINT PK_MapSpawnPoint PRIMARY KEY(ID));
CREATE TABLE MapType(
	ID integer NOT NULL,
	Name varchar(64) NOT NULL
);
CREATE TABLE MimicSpawn(
	MapID integer NOT NULL,
	MimicName integer NOT NULL,
	SpawnChance integer NOT NULL,
	MinDelayBetweenSpawn integer NOT NULL
);
CREATE TABLE MixEffect(
	ID smallint GENERATED ALWAYS AS IDENTITY NOT NULL,
	Code integer NOT NULL,
	BeforeValue varchar(16) NOT NULL,
	AfterValue varchar(16) NOT NULL,
 CONSTRAINT PK_MixEffect PRIMARY KEY(ID));
CREATE TABLE MixEffectType(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	AfterText varchar(16) NULL,
 CONSTRAINT PK_MixEffectType PRIMARY KEY(ID));
CREATE TABLE MixItem(
	ID smallint GENERATED ALWAYS AS IDENTITY NOT NULL,
	MixID smallint NOT NULL,
	ItemSubTypeID integer NOT NULL,
 CONSTRAINT PK_MixItem PRIMARY KEY(ID));
CREATE TABLE MixList(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	MixUniqueID integer NOT NULL,
	GroupMixID integer NOT NULL,
	TypeMix integer NOT NULL,
	TypeMixName varchar(20) NOT NULL,
	Description varchar(150) NOT NULL,
	Lucidy integer NOT NULL,
	Sereneo integer NOT NULL,
	Fadeo integer NOT NULL,
	Sparky integer NOT NULL,
	Raident integer NOT NULL,
	Transparo integer NOT NULL,
	Murky integer NOT NULL,
	Devine integer NOT NULL,
	Celesto integer NOT NULL,
	Mirage integer NOT NULL,
	Inferna integer NOT NULL,
	Enigma integer NOT NULL,
	Bellum integer NOT NULL,
	Oredo integer NOT NULL,
	NewSheltom14 integer NULL,
	NewSheltom15 integer NULL,
	TypeAtributte integer NOT NULL,
	Atributte real NOT NULL,
	PerAtributte integer NOT NULL,
	TypeAtributte2 integer NOT NULL,
	Atributte2 real NOT NULL,
	PerAtributte2 integer NOT NULL,
	TypeAtributte3 integer NOT NULL,
	Atributte3 real NOT NULL,
	PerAtributte3 integer NOT NULL,
	TypeAtributte4 integer NOT NULL,
	Atributte4 real NOT NULL,
	PerAtributte4 integer NOT NULL,
	TypeAtributte5 integer NOT NULL,
	Atributte5 real NOT NULL,
	PerAtributte5 integer NOT NULL,
	TypeAtributte6 integer NOT NULL,
	Atributte6 real NOT NULL,
	PerAtributte6 integer NOT NULL,
	TypeAtributte7 integer NOT NULL,
	Atributte7 real NOT NULL,
	PerAtributte7 integer NOT NULL,
	TypeAtributte8 integer NOT NULL,
	Atributte8 real NOT NULL,
	PerAtributte8 integer NOT NULL,
 CONSTRAINT PK_MixList PRIMARY KEY(ID));
CREATE TABLE MixValue(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	MixID smallint NOT NULL,
	EffectID smallint NOT NULL,
	Value double precision NOT NULL,
	EffectTypeID integer NOT NULL,
 CONSTRAINT PK_MixValue PRIMARY KEY(ID));
CREATE TABLE ModelAnimationList(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	ModelID integer NOT NULL,
	Type integer NOT NULL,
	FrameBegin integer NOT NULL,
	FrameEnd integer NOT NULL,
	FrameEvent1 integer NOT NULL,
	FrameEvent2 integer NOT NULL,
	FrameEvent3 integer NOT NULL,
	FrameEvent4 integer NOT NULL,
 CONSTRAINT PK_ModelAnimationList PRIMARY KEY(ID));
CREATE TABLE ModelList(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	Model varchar(64) NOT NULL,
	Width integer NOT NULL,
	Height integer NOT NULL,
	DeathModelID integer NOT NULL,
 CONSTRAINT PK_ModelList PRIMARY KEY(ID));
CREATE TABLE MonsterEffect(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	Code integer NOT NULL,
	Name varchar(32) NOT NULL,
 CONSTRAINT PK_MonsterEffect PRIMARY KEY(ID));
CREATE TABLE MonsterList(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	Name varchar(32) NULL,
	ModelFile varchar(64) NULL,
	Level integer NULL,
	Glow integer NULL,
	Size real NULL,
	CameraY integer NULL,
	CameraZ integer NULL,
	MonsterID integer NULL,
	DropIsPublic integer NULL,
	DropQuantity integer NULL,
	SpawnTime varchar(50) NULL,
	SpawnMin integer NULL,
	SpawnMax integer NULL,
	Inteligence integer NULL,
	MonsterType varchar(30) NULL,
	ViewSight integer NULL,
	HP integer NULL,
	EXP varchar(50) NULL,
	SpecialSkillType varchar(50) NULL,
	SpecialSkillHit varchar(50) NULL,
	SpecialHitRate integer NULL,
	SpecialHitScope integer NULL,
	SpecialHitPowerMin integer NULL,
	SpecialHitPowerMax integer NULL,
	ATKPowMin integer NULL,
	ATKPowMax integer NULL,
	Absorb integer NULL,
	Stunchance integer NOT NULL,
	Block integer NULL,
	Defense integer NULL,
	AttackSpeed integer NULL,
	AttackRating integer NULL,
	AttackRange integer NULL,
	PerfectAttackRate integer NULL,
	SizeShadow varchar(30) NULL,
	Organic integer NULL,
	Lightning integer NULL,
	Ice integer NULL,
	Fire integer NULL,
	Poison integer NULL,
	Magic integer NULL,
	PropertyMon varchar(30) NULL,
	MoveSpeed integer NULL,
	PotionPercent integer NULL,
	Potions integer NULL,
	Effect varchar(50) NULL,
	QuestItemDrop varchar(50) NULL,
	QuestID integer NULL,
	QuestMap integer NULL,
	Stage varchar(50) NULL,
	HealthPoint integer NULL,
 CONSTRAINT PK_MonsterList PRIMARY KEY(ID));
CREATE TABLE NPCList(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	Name varchar(64) NOT NULL,
	GameFile varchar(250) NOT NULL,
	Message1 varchar(250) NULL,
	Message2 varchar(250) NULL,
	Message3 varchar(250) NULL,
	Message4 varchar(250) NULL,
	EventType integer NOT NULL,
	EventParam integer NOT NULL,
	SkillQuests integer NOT NULL,
	QuestID integer NOT NULL,
	QuestTypeID integer NOT NULL,
	QuestTypeSubID integer NOT NULL,
	TeleportID integer NOT NULL,
	WeaponShop varchar(1024) NULL,
	DefenseShop varchar(1024) NULL,
	MiscShop varchar(1024) NULL,
 CONSTRAINT PK_NPCList PRIMARY KEY(ID));
CREATE TABLE NPCMessage(
	NPCID integer NOT NULL,
	Message varchar(128) NOT NULL
);
CREATE TABLE PetSystem(
	id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	PetOwnerName varchar(32) NULL,
	PetName varchar(32) NULL,
	PetSkinId integer NOT NULL,
PRIMARY KEY(ID));
CREATE TABLE PetSystemSkin(
	id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	PetNameSummon varchar(32) NOT NULL,
	PetSize double precision NULL,
	PetRarity integer NOT NULL,
PRIMARY KEY(ID));
CREATE TABLE QuestEventList(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	QuestID integer NOT NULL,
	PercentIncreaseEXP integer NOT NULL,
	DropReduction integer NOT NULL
);
CREATE TABLE QuestList(
	ID integer NOT NULL,
	Name varchar(64) NOT NULL,
	ShortDescription varchar(128) NOT NULL,
	Description varchar(2048) NOT NULL,
	ProgressText varchar(2048) NOT NULL,
	ConclusionText varchar(2048) NOT NULL,
	Party integer NOT NULL,
	Multiple integer NOT NULL,
	PVP integer NOT NULL,
	MinLevel integer NULL,
	MaxLevel integer NULL,
	MaxDuration integer NULL,
	DurationType integer NULL,
	WaitTime integer NULL,
	MapID varchar(64) NULL,
	MonsterID varchar(64) NULL,
	RequiredItems varchar(128) NULL,
	QuestType integer NOT NULL,
	RequiredQuestIDs varchar(64) NULL,
	InclusionQuestIDs varchar(64) NULL,
	NPCID integer NOT NULL,
	ProgressNPCID integer NOT NULL,
	ConclusionNPCID integer NOT NULL,
	AutoStartQuestID integer NULL,
	ClassRestriction varchar(32) NULL,
	AreaType integer NULL,
	MinX integer NULL,
	MaxX integer NULL,
	MinZ integer NULL,
	MaxZ integer NULL,
	Radius integer NULL
);
CREATE TABLE QuestRewardList(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	QuestID integer NOT NULL,
	Name varchar(64) NULL,
	MonsterQuantities varchar(64) NULL,
	RequiredDropQuantities varchar(64) NULL,
	EXPReward bigint NOT NULL,
	EXPPotBonus integer NOT NULL,
	EXPLevelDifference integer NOT NULL,
	ItemRewardSelect integer NULL,
	ItemsReward varchar(128) NULL,
	ItemsRewardQuantities varchar(64) NULL,
	ExtraRewardType varchar(64) NULL,
	ExtraRewardValues varchar(64) NULL,
	TimeMultiplier integer NULL,
 CONSTRAINT PK_QuestRewardList PRIMARY KEY 
(
	QuestID 
)
);
CREATE TABLE QuestSwapList(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	QuestRace1 integer NOT NULL,
	QuestRace2 integer NOT NULL,
	QuestRace3 integer NOT NULL,
 CONSTRAINT PK_QuestSwapList PRIMARY KEY(ID));
CREATE TABLE QuestWindowList(
	ID integer GENERATED ALWAYS AS IDENTITY NOT NULL,
	NPCID integer NOT NULL,
	QuestListID varchar(255) NOT NULL,
	MainImage varchar(255) NOT NULL,
	MainText varchar(255) NOT NULL
);
CREATE TABLE RarityChance(
	RarityChanceGroup integer NOT NULL,
	Rarity integer NOT NULL,
	Chance integer NOT NULL
);
CREATE TABLE RarityChanceGroup(
	ID integer NOT NULL,
	MinLevel integer NOT NULL,
	MaxLevel integer NOT NULL,
 CONSTRAINT PK_RarityLevelGroups PRIMARY KEY(ID));
CREATE TABLE RarityChanceMod(
	Type integer NOT NULL,
	ModCommon real NOT NULL,
	ModUncommon real NOT NULL,
	ModRare real NOT NULL,
	ModEpic real NOT NULL,
	ModLegendary real NOT NULL,
 CONSTRAINT PK_RarityChanceMod PRIMARY KEY 
(
	Type 
)
);
